<?php

declare(strict_types=1);

namespace Commet\Resources;

use Commet\ApiResponse;
use Commet\Enums\DiscountType;
use Commet\HttpClient;
use Commet\Models\PromoCode;

// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.
class PromoCodesResource
{
    public function __construct(
        private readonly HttpClient $http,
    ) {}

    /**
     * List promo codes with cursor-based pagination.
     * @return ApiResponse<PromoCode[]>
     */
    public function list(
        ?int $limit = null,
        ?string $cursor = null,
    ): ApiResponse {
        $response = $this->http->get(
            "/promo-codes",
            HttpClient::buildBody([
                "limit" => $limit,
                "cursor" => $cursor,
            ]),
        );

        if ($response->success && is_array($response->data)) {
            $items = array_map(
                fn(array $item) => PromoCode::fromArray($item),
                $response->data,
            );

            return new ApiResponse(
                success: true,
                data: $items,
                code: $response->code,
                message: $response->message,
                hasMore: $response->hasMore,
                nextCursor: $response->nextCursor,
            );
        }

        return $response;
    }

    /**
     * Retrieve a promo code by its public ID.
     * @return ApiResponse<PromoCode>
     */
    public function get(
        string $id,
    ): ApiResponse {
        $response = $this->http->get(
            "/promo-codes/{$id}",
        );

        if ($response->success && is_array($response->data)) {
            return new ApiResponse(
                success: true,
                data: PromoCode::fromArray($response->data),
                code: $response->code,
                message: $response->message,
            );
        }

        return $response;
    }

    /**
     * Create a new promo code. Optionally restrict to specific plans.
     * @param string[]|null $planIds
     * @return ApiResponse<PromoCode>
     */
    public function create(
        string $code,
        DiscountType $discountType,
        int $discountValue,
        ?int $durationCycles = null,
        ?int $maxRedemptions = null,
        ?string $expiresAt = null,
        ?array $planIds = null,
        ?string $idempotencyKey = null,
    ): ApiResponse {
        $response = $this->http->post(
            "/promo-codes",
            HttpClient::buildBody([
                "code" => $code,
                "discount_type" => $discountType->value,
                "discount_value" => $discountValue,
                "duration_cycles" => $durationCycles,
                "max_redemptions" => $maxRedemptions,
                "expires_at" => $expiresAt,
                "plan_ids" => $planIds,
            ]),
            idempotencyKey: $idempotencyKey,
        );

        if ($response->success && is_array($response->data)) {
            return new ApiResponse(
                success: true,
                data: PromoCode::fromArray($response->data),
                code: $response->code,
                message: $response->message,
            );
        }

        return $response;
    }

    /**
     * Update a promo code's redemption limits, expiration, active status, or plan restrictions.
     * @param string[]|null $planIds
     * @return ApiResponse<PromoCode>
     */
    public function update(
        string $id,
        ?int $maxRedemptions = null,
        ?string $expiresAt = null,
        ?bool $active = null,
        ?array $planIds = null,
        ?string $idempotencyKey = null,
    ): ApiResponse {
        $response = $this->http->put(
            "/promo-codes/{$id}",
            HttpClient::buildBody([
                "max_redemptions" => $maxRedemptions,
                "expires_at" => $expiresAt,
                "active" => $active,
                "plan_ids" => $planIds,
            ]),
            idempotencyKey: $idempotencyKey,
        );

        if ($response->success && is_array($response->data)) {
            return new ApiResponse(
                success: true,
                data: PromoCode::fromArray($response->data),
                code: $response->code,
                message: $response->message,
            );
        }

        return $response;
    }
}
