<?php

declare(strict_types=1);

namespace Commet\Resources;

use Commet\ApiResponse;
use Commet\Enums\TransactionStatus;
use Commet\HttpClient;
use Commet\Models\Transaction;
use Commet\Models\TransactionRefund;
use Commet\Models\TransactionRetry;

// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.
class TransactionsResource
{
    public function __construct(
        private readonly HttpClient $http,
    ) {}

    /**
     * List payment transactions with cursor-based pagination. Filter by status or customer email.
     * @return ApiResponse<Transaction[]>
     */
    public function list(
        ?TransactionStatus $status = null,
        ?string $customerEmail = null,
        ?int $limit = null,
        ?string $cursor = null,
    ): ApiResponse {
        $response = $this->http->get(
            "/transactions",
            HttpClient::buildBody([
                "status" => $status?->value,
                "customer_email" => $customerEmail,
                "limit" => $limit,
                "cursor" => $cursor,
            ]),
        );

        if ($response->success && is_array($response->data)) {
            $items = array_map(
                fn(array $item) => Transaction::fromArray($item),
                $response->data,
            );

            return new ApiResponse(
                success: true,
                data: $items,
                code: $response->code,
                message: $response->message,
                hasMore: $response->hasMore,
                nextCursor: $response->nextCursor,
            );
        }

        return $response;
    }

    /**
     * Retrieve a single payment transaction by its public ID, including provider details.
     * @return ApiResponse<Transaction>
     */
    public function get(
        string $id,
    ): ApiResponse {
        $response = $this->http->get(
            "/transactions/{$id}",
        );

        if ($response->success && is_array($response->data)) {
            return new ApiResponse(
                success: true,
                data: Transaction::fromArray($response->data),
                code: $response->code,
                message: $response->message,
            );
        }

        return $response;
    }

    /**
     * Issue a full refund for a payment transaction.
     * @return ApiResponse<TransactionRefund>
     */
    public function refund(
        string $id,
        ?string $idempotencyKey = null,
    ): ApiResponse {
        $response = $this->http->post(
            "/transactions/{$id}/refund",
            idempotencyKey: $idempotencyKey,
        );

        if ($response->success && is_array($response->data)) {
            return new ApiResponse(
                success: true,
                data: TransactionRefund::fromArray($response->data),
                code: $response->code,
                message: $response->message,
            );
        }

        return $response;
    }

    /**
     * Retry a failed payment transaction. Creates a new invoice and initiates a new payment attempt.
     * @return ApiResponse<TransactionRetry>
     */
    public function retry(
        string $id,
        ?string $idempotencyKey = null,
    ): ApiResponse {
        $response = $this->http->post(
            "/transactions/{$id}/retry",
            idempotencyKey: $idempotencyKey,
        );

        if ($response->success && is_array($response->data)) {
            return new ApiResponse(
                success: true,
                data: TransactionRetry::fromArray($response->data),
                code: $response->code,
                message: $response->message,
            );
        }

        return $response;
    }
}
